Login: #登录模块！
  login: #登录接口
    path:  /api/auth/login #登录路径
    method: POST
  logout: #登出接口
    path:  "xxxx" #登录路径
    method: POST

User: #用户模块
  create: #增加
    path: /api/admin/user/create  #增加
    method: POST
  delete: #删除,读取这里的，不读xls的URI
    path: /api/admin/user/delete?id=6  #删除
    method: POST
  update: #修改
    path: /api/admin/user/update
    method: POST
  query: #查询
    path:  /api/admin/user/list #查询全部
    method: GET
  get_one: #单个查询
    path:  /api/admin/user/get?id=3 #查询id /api/admin/user/get?id=3
    method: GET

Storage: #存储模块
  query: #查询
    path:  /api/admin/storage/list #查询全部
    method: GET